import { ImageType, RenderMode, ViewMode } from "../../shared/enums";
import type { ViewerChannelSetting } from "../../shared/utils/viewerChannelSettings";
import type { ChannelState, ViewerChannelStateParams, ViewerState, ViewerStateParams } from "../types";

export const DEFAULT_TEST_VIEWER_STATE: ViewerState = {
  viewMode: ViewMode.threeD, // "XY", "XZ", "YZ"
  renderMode: RenderMode.volumetric, // "pathtrace", "maxproject"
  imageType: ImageType.segmentedCell,
  showAxes: false,
  showBoundingBox: false,
  backgroundColor: [0, 0, 0],
  boundingBoxColor: [255, 255, 255],
  autorotate: false,
  maskAlpha: 0,
  brightness: 70,
  density: 50,
  levels: [35, 140, 255],
  interpolationEnabled: true,
  region: { x: [0, 1], y: [0, 1], z: [0, 1] },
  slice: { x: 0.5, y: 0.5, z: 0.5 },
  time: 0,
  scene: 0,
  cameraState: undefined,
  singleChannelMode: false,
  singleChannelIndex: 0,
  useExactScaleLevel: false,
  scaleLevelIndex: 0,
};

export const SERIALIZED_DEFAULT_TEST_VIEWER_STATE: ViewerStateParams = {
  mode: "volumetric",
  view: "3D",
  image: "cell",
  axes: "0",
  bb: "0",
  bgcol: "000000",
  bbcol: "ffffff",
  rot: "0",
  mask: "0",
  bright: "70",
  dens: "50",
  lvl: "35,140,255",
  interp: "1",
  reg: "0:1,0:1,0:1",
  slice: "0.5,0.5,0.5",
  t: "0",
  scene: "0",
  scm: "0",
  sci: "0",
  esl: "0",
  scl: "0",
};

export const CUSTOM_TEST_VIEWER_STATE: ViewerState = {
  renderMode: RenderMode.pathTrace,
  viewMode: ViewMode.xy,
  imageType: ImageType.fullField,
  showAxes: true,
  showBoundingBox: true,
  backgroundColor: [255, 0, 0],
  boundingBoxColor: [0, 255, 0],
  autorotate: true,
  maskAlpha: 55,
  brightness: 100,
  density: 75,
  levels: [0, 250, 251],
  interpolationEnabled: false,
  region: { x: [0, 0.5], y: [0, 1], z: [0, 1] },
  slice: { x: 0.25, y: 0.75, z: 0.5 },
  time: 100,
  scene: 3,
  singleChannelMode: true,
  singleChannelIndex: 3,
  useExactScaleLevel: true,
  scaleLevelIndex: 3,
  cameraState: {
    position: [-1.05, -4, 45],
    target: [0, 0, 0],
    up: [0, 1, 0],
    orthoScale: 3.534,
    fov: 43.5,
  },
};

export const SERIALIZED_CUSTOM_TEST_VIEWER_STATE: ViewerStateParams = {
  mode: "pathtrace",
  view: "Z",
  image: "fov",
  axes: "1",
  bb: "1",
  bgcol: "ff0000",
  bbcol: "00ff00",
  rot: "1",
  mask: "55",
  bright: "100",
  dens: "75",
  lvl: "0,250,251",
  interp: "0",
  reg: "0:0.5,0:1,0:1",
  slice: "0.25,0.75,0.5",
  t: "100",
  scene: "3",
  scm: "1",
  sci: "3",
  esl: "1",
  scl: "3",
  cam: "pos:-1.05:-4:45,tar:0:0:0,up:0:1:0,ort:3.534,fov:43.5",
};

export const DEFAULT_TEST_CHANNEL_STATE: ChannelState = {
  name: "",
  displayName: "",
  color: [255, 0, 0],
  volumeEnabled: true,
  isosurfaceEnabled: true,
  isovalue: 128,
  opacity: 0.75,
  colorizeEnabled: true,
  colorizeAlpha: 0.5,
  useControlPoints: false,
  controlPoints: [
    { x: 0, opacity: 0.5, color: [255, 255, 255] },
    { x: 255, opacity: 1.0, color: [255, 255, 255] },
  ],
  ramp: [0, 255],
  plotMin: 0,
  plotMax: 255,
  keepIntensityRange: false,
};

export const SERIALIZED_DEFAULT_TEST_CHANNEL_STATE: ViewerChannelStateParams = {
  col: "ff0000",
  ven: "1",
  sen: "1",
  isv: "128",
  isa: "0.75",
  clz: "1",
  cza: "0.5",
  cpe: "0",
  cpt: "0:0.5:1:255:1:1",
  ram: "0:255",
  pin: "0",
};

export const DEFAULT_TEST_VIEWER_CHANNEL_SETTING: ViewerChannelSetting = {
  match: 0,
  color: undefined,
  enabled: undefined,
  surfaceEnabled: undefined,
  isovalue: undefined,
  surfaceOpacity: undefined,
  colorizeEnabled: undefined,
  colorizeAlpha: undefined,
};
