# Adapted from https://github.com/marketplace/actions/deploy-pr-preview.
name: GitHub Pages PR Preview

env:
  NODE_VERSION: "24"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 #v6.2.0
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "npm"

        # Must override default webpack build base so that assets can still be accessed when not placed in the root directory of gh-pages branch.
      - name: Install and Build
        run: npm ci && webpack --config webpack.dev.js --env env=production basename=/vole-app/pr-preview/pr-${PR_NUMBER}/
        env:
          PR_NUMBER: ${{ github.event.number }}

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@430e3dfc1de8a8ae77e77d862d25676ef9db55d1
        with:
          source-dir: ./imageviewer/
